name-template: 'Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '变更说明'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '修复说明'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '易用性改进'
    labels:
      - 'ease of use'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Release date: xxx年xx月xx日

  代码变更: https://github.com/hhyo/Archery/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
  贡献者: $CONTRIBUTORS

  $CHANGES

  ## 升级步骤
  - https://github.com/hhyo/archery/wiki/upgrade
