# Generated by Django 2.2.1 on 2019-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('menu_sqlupdate', '菜单 数据库更新'),),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(max_length=50, verbose_name='实例名称')),
                ('db_name', models.CharField(max_length=30, verbose_name='数据库名称')),
                ('sqllog', models.TextField(verbose_name='执行的sql更新')),
                ('effect_row', models.TextField(verbose_name='执行信息')),
                ('cost_time', models.CharField(default='', max_length=10, verbose_name='执行耗时')),
                ('username', models.CharField(max_length=30, verbose_name='操作人')),
                ('user_display', models.CharField(default='', max_length=50, verbose_name='操作人中文名')),
                ('priv_check', models.IntegerField(choices=[(1, ' 正常'), (2, '跳过')], default=0, verbose_name='更新权限是否正常校验')),
                ('hit_rule', models.IntegerField(choices=[(0, '未知'), (1, '命中'), (2, '未命中')], default=0, verbose_name='更新是否命中脱敏规则')),
                ('masking', models.IntegerField(choices=[(1, '是'), (2, '否')], default=0, verbose_name='更新结果是否正常脱敏')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('sys_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '更新日志',
                'verbose_name_plural': '更新日志',
                'db_table': 'update_log',
                'managed': True,
            },
        ),
    ]
