apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "goinception.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "goinception.name" . }}
    helm.sh/chart: {{ include "goinception.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "goinception.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "goinception.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: goinception
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: goinception
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: goinception-config-volume
              subPath: config.toml
              mountPath: /etc/config.toml
      volumes:
        - name: goinception-config-volume
          configMap:
            name: goinception-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
