# -*- coding: UTF-8 -*- 

from django.conf.urls import url

from . import views, views_ajax, query, slowlog, instance, db_diagnostics, charts, sql_tuning
from sql.utils import jobs

urlpatterns = [
    url(r'^$', views.sqlworkflow, name='sqlworkflow'),
    url(r'^index/$', views.sqlworkflow, name='sqlworkflow'),
    url(r'^login/$', views.login, name='login'),
    url(r'^sign_up/$', views.sign_up, name='sign_up'),
    url(r'^logout/$', views.sign_out, name='logout'),
    url(r'^submitsql/$', views.submitSql, name='submitSql'),
    url(r'^editsql/$', views.submitSql, name='editsql'),
    url(r'^submitothercluster/$', views.submitSql, name='submitothercluster'),
    url(r'^sqlworkflow/$', views.sqlworkflow, name='sqlworkflow'),

    url(r'^autoreview/$', views.autoreview, name='autoreview'),
    url(r'^detail/(?P<workflowId>[0-9]+)/$', views.detail, name='detail'),
    url(r'^passed/$', views.passed, name='passed'),
    url(r'^execute/$', views.execute, name='execute'),
    url(r'^timingtask/$', views.timingtask, name='timingtask'),
    url(r'^cancel/$', views.cancel, name='cancel'),
    url(r'^rollback/$', views.rollback, name='rollback'),
    url(r'^sqlquery/$', views.sqlquery, name='sqlquery'),
    url(r'^slowquery/$', views.slowquery, name='slowquery'),
    url(r'^sqladvisor/$', views.sqladvisor, name='sqladvisor'),
    url(r'^slowquery_advisor/$', views.sqladvisor, name='slowquery_advisor'),
    url(r'^queryapplylist/$', views.queryapplylist, name='queryapplylist'),
    url(r'^queryapplydetail/(?P<apply_id>[0-9]+)/$', views.queryapplydetail, name='queryapplydetail'),
    url(r'^queryuserprivileges/$', views.queryuserprivileges, name='queryuserprivileges'),
    url(r'^diagnostic_process/$', views.diagnostic_process, name='diagnostic_process'),
    url(r'^diagnostic_sapce/$', views.diagnostic_sapce, name='diagnostic_sapce'),
    url(r'^workflow/$', views.workflows, name='workflows'),
    url(r'^workflowdetail/(?P<audit_id>[0-9]+)/$', views.workflowsdetail, name='workflowsdetail'),
    url(r'^dbaprinciples/$', views.dbaprinciples, name='dbaprinciples'),
    url(r'^charts/$', charts.pyecharts, name='charts'),
    url(r'^config/$', views.config, name='config'),

    url(r'^authenticate/$', views_ajax.authenticateEntry, name='authenticate'),
    url(r'^sqlworkflowlist/$', views_ajax.sqlworkflowlist, name='sqlworkflowlist'),
    url(r'^simplecheck/$', views_ajax.simplecheck, name='simplecheck'),
    url(r'^getOscPercent/$', views_ajax.getOscPercent, name='getOscPercent'),
    url(r'^getWorkflowStatus/$', views_ajax.getWorkflowStatus, name='getWorkflowStatus'),
    url(r'^stopOscProgress/$', views_ajax.stopOscProgress, name='stopOscProgress'),
    url(r'^sqladvisorcheck/$', views_ajax.sqladvisorcheck, name='sqladvisorcheck'),
    url(r'^sql_tuning/$', sql_tuning.tuning, name='sql_tuning'),
    url(r'^workflowlist/$', views_ajax.workflowlist, name='workflowlist'),
    url(r'^group_relations/$', views_ajax.group_relations, name='group_relations'),
    url(r'^group_auditors/$', views_ajax.group_auditors, name='group_auditors'),
    url(r'^changegroupauditors/$', views_ajax.changegroupauditors, name='changegroupauditors'),
    url(r'^changeconfig/$', views_ajax.changeconfig, name='changeconfig'),

    url(r'^getdbNameList/$', instance.getdbNameList, name='getdbNameList'),
    url(r'^getTableNameList/$', instance.getTableNameList, name='getTableNameList'),
    url(r'^getColumnNameList/$', instance.getColumnNameList, name='getColumnNameList'),
    url(r'^getqueryapplylist/$', query.getqueryapplylist, name='getqueryapplylist'),
    url(r'^getuserprivileges/$', query.getuserprivileges, name='getuserprivileges'),
    url(r'^applyforprivileges/$', query.applyforprivileges, name='applyforprivileges'),
    url(r'^modifyqueryprivileges/$', query.modifyqueryprivileges, name='modifyqueryprivileges'),
    url(r'^queryprivaudit/$', query.queryprivaudit, name='queryprivaudit'),
    url(r'^query/$', query.query, name='query'),
    url(r'^querylog/$', query.querylog, name='querylog'),
    url(r'^explain/$', query.explain, name='explain'),
    url(r'^slowquery_review/$', slowlog.slowquery_review, name='slowquery_review'),
    url(r'^slowquery_review_history/$', slowlog.slowquery_review_history, name='slowquery_review_history'),
    url(r'^del_sqlcronjob/$', jobs.del_sqlcronjob, name='del_sqlcronjob'),

    url(r'^process_status/$', db_diagnostics.process_status, name='process_status'),
    url(r'^create_kill_session/$', db_diagnostics.create_kill_session, name='create_kill_session'),
    url(r'^kill_session/$', db_diagnostics.kill_session, name='kill_session'),
    url(r'^sapce_status/$', db_diagnostics.sapce_status, name='sapce_status'),

]
